### ISSUE TITLE
User Creation

### ISSUE THREAD

**Issue by tjkopena** [tom5760/arch-install#1]
I think there might be two issues in the part where it attempts to create a primary user:
- I had set the password variable to blank, and the script seemed to just blow through setting the password, with no input from me.
- The adbuser and wireshark groups don't exist when the command runs, so the useradd call as-is doesn't work.

I will be installing another machine later in the week so I will double check that these are problems.

**Comment by tom5760** [comment]
I'm not sure why the script wouldn't ask for a password, I'll have to double-check it in a VM or something.

For the second point, unless the `android-udev` and `wireshark-gtk` packages didn't get installed, those groups should exist.  Maybe somehow one of those packages failed to install?

**Comment by tjkopena** [comment]
I could not repeat this behavior, not sure what happened on the other machine.
